[package]
name = "clinic_core"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true}
tracing-actix-web = { workspace = true }
tracing = { workspace = true }
mongodb = { workspace = true }
# import internally libraries below, and Rust crates above
appointment_service = { path = "../appointment_service"}
doctor_service = { path = "../doctor_service"}
patient_service = { path = "../patient_service"}
common = { path = "../common" } # contains all shared services like DB, logging etc