[package]
name = "patient_service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true}
tracing = { workspace = true }
serde = { workspace = true }
mongodb = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
validator = { workspace = true }
strum = { workspace = true }
chrono = { workspace = true }
common = { path = "../common" } # import the DB helper from here