[package]
name = "doctor_service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true}
tracing = { workspace = true }
serde = { workspace = true }
validator = { workspace = true }
chrono = { workspace = true }
mongodb = { workspace = true }
strum = { workspace = true }
common = { path = "../common" } # internal workspace import