name: patient-service-test
on:
  push:
    branches: [dev, feature/*]
    paths:
      - 'patient_service/**'
      - 'common/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/test-patient.yml'
  pull_request:
    branches: [main]
    paths:
      - 'patient_service/**'
      - 'common/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/test-patient.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-patient-service:
    name: Test patient-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workdir: "."

      - name: Pre-pull test images
        run: |
          docker pull mongo:8.3-rc-noble
          docker pull jaegertracing/jaeger:2.14.1

      - name: Run Tests for patient_service
        run: cargo test -p patient_service --test handler_tests -- --test-threads=1
